#! /usr/bin/env python                                                          
# -*- coding:utf-8 -*-                                                          

import matplotlib.pyplot as plt
from matplotlib import rc

import pylab
import glob

width = 5
height = 4

params = {'backend': 'eps',                                 
          'axes.labelsize': 10,                
          'text.fontsize': 10,　　　　　　               
          'legend.fontsize': 10,                           
          'xtick.labelsize': 5,                     
          'ytick.labelsize': 5,                      
          'text.usetex': False,      
          'figure.figsize': [width, height]}        
pylab.rcParams.update(params)

#rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

fig = plt.figure()
fig.subplots_adjust(wspace = 0.5, hspace = 0.1)

filenames = glob.glob("./target*.txt")
filenames.sort()
print filenames

ax = []

num = 0
for filename in filenames:
    num += 1

print num

i = 0
for filename in filenames:
    ax.append(fig.add_subplot(num / 2, 2, i + 1, aspect = "equal"))

    #ax[i].set_xlabel("X")
    #ax[i].set_ylabel("Y")

    target_x = []
    target_y = []
    file = open(filename, "r")
    for line in file:
        items = line.split("\t")
        target_x.append(float(items[0]))
        target_y.append(float(items[1]))

    ax[i].plot(target_x, target_y, ".")

    ax[i].set_xlim(-1, 1)
    ax[i].set_xticks((-1, 0, 1))

    ax[i].set_ylim(-1, 1)
    ax[i].set_yticks((-1, 0, 1))

    i += 1

fig.savefig("fig.eps")
fig.show()
raw_input()
